# configurable settings
model:
  name: "gemini-robotics-er-1.5-preview"
  # other models
        # gemini-robotics-er-1.5-preview
        # gemini-2.5-flash-lite
        # gemini-3-pro-preview
        # gemini-3-flash-preview

joint positions:
  home: # overlook position
    - 359.9328308105469
    - 4.317113399505615
    - 179.1765899658203
    - 267.7507019042969
    - 359.4789123535156
    - 278.1408996582031
    - 89.97930145263672